### ISSUE TITLE
Mid-page CTA

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-home#11]
Replace: Get your first tips today

TBD, maybe delete this section

**Comment by chrtannus** [comment]
One idea:

----
**Get your first results**
In just under a minute, we'll walk you through a few questions to find the perfect tool for your needs. You don't even need to create an account or provide any personal information.

----

<img width="858" alt="home-cta-1" src="https://github.com/cytoscape/cytoscape-home/assets/989686/22297514-050b-4aad-9c63-01b8646a9264">
