### ISSUE TITLE
Citations section

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-home#12]
Replace: Everyone is changing their life with Pocket.

- [x] Replace reviews with citations
- [x] Update design: authors, title, journal, year, no stars
- [X] Link to a related papers search
- [ ] Get list of prominent citations, recent
- [ ] Explore auto-updates for recent ones

**Comment by chrtannus** [comment]
<img width="1389" alt="cyhome-citations" src="https://github.com/cytoscape/cytoscape-home/assets/989686/5f4737fb-b94b-447f-ac23-5329576f3062">

**Comment by gbader** [comment]
Typo: researchers
