### ISSUE TITLE
Links to Cytoscape and Cytoscape Web

### ISSUE THREAD

**Issue by chrtannus** [cytoscape/cytoscape-home#22]
The hero section (or the header) should have links to:
- Cytoscape (desktop) website: cytoscape.org
- Cytoscape Web: use https://web-stage.cytoscape.org/ for now

They should probably be styled as buttons or have different colors/icons to make them more noticeable by the user.
Or it may be better to have only one button (e.g. "Use Cytoscape"), which would open a box/dialog where the two options (web, desktop) could be presented (with their link outs). This would allow us to write a more detailed explanation for each option (pros/cons, etc.), along with more representative figures, such as screenshots.

**Comment by maxkfranz** [comment]
Closing.  Can reopen if needed later

**Comment by chrtannus** [comment]
- _`Where is the old site?`_ link:

<img width="1010" height="637" alt="Image" src="https://github.com/user-attachments/assets/6ccec1a9-a280-4190-ac72-b6a45feb06ee" />

<img width="40%" height="40%" alt="Image" src="https://github.com/user-attachments/assets/9711329c-4676-4e04-9080-776d111de176" />
<br><br>

- Cytoscape comparison section (Web vs Desktop):

<img width="1007" height="633" alt="Image" src="https://github.com/user-attachments/assets/56155863-6e25-465f-8b91-f10b7484ae28" />
