### ISSUE TITLE
Update logo and favicon

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-home#5]
There is currently a blue placeholder icon: https://cytoscape-home.pages.dev

- [x] Replace icon on page at top
- [x] Replace favicon
- [ ] Double check logo isn't used anywhere else. If so, also update it.

**Comment by chrtannus** [comment]
First version:

----
<img width="126" alt="home-logo-1" src="https://github.com/cytoscape/cytoscape-home/assets/989686/60ab8078-4734-4d01-8040-373f6bbbef3f">

----
<img width="353" alt="home-favicon-screenshot" src="https://github.com/cytoscape/cytoscape-home/assets/989686/95ab3dba-96c4-4482-b790-7a3a50c77513">

**Comment by chrtannus** [comment]
Here is another option:

<img width="466" alt="logo-favicon-2" src="https://github.com/cytoscape/cytoscape-home/assets/989686/3ef756c7-50c6-4f50-8d64-220b09d498b0">
