### ISSUE TITLE
Hero section - CTA

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-home#6]
- [x] Replace App Store call-to-action buttons with black 'Get Started'
- [ ] Stub out an alert on the new CTA buttons, like 'will be linked to wizards cards in future'
- [ ] Comment out the video button until we have one

**Comment by chrtannus** [comment]
<img width="1305" alt="hero" src="https://github.com/cytoscape/cytoscape-home/assets/989686/80596995-3124-49fe-95ee-c3ef6776689b">

**Comment by chrtannus** [comment]
New Hero section with search box:

<img width="1196" height="702" alt="Image" src="https://github.com/user-attachments/assets/ded334ca-dafc-4686-9c1c-13778d0407a6" />
