### ISSUE TITLE
Hero section - text

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-home#7]
- [ ] Update tag line, TBD
- [ ] Update description text

Use this issue to plan out the text before updating.

**Comment by chrtannus** [comment]
Initial idea:

----
**Transform your bioinformatics research**

Finding the perfect tool to search or create biological network figures has never been easier. Whether you are exploring genes, proteins or pathways, our intuitive interface allows you to analyze your data and create beautiful figures that are ready to be published.

----

<img width="1148" alt="home-top-draft-1" src="https://github.com/cytoscape/cytoscape-home/assets/989686/9aba1610-bf01-4f64-82f9-f3da30f305e9">
