### ISSUE TITLE
Feature section

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-home#9]
Replace this: Every feature you need to win. Try it for yourself.

- [x] New top description text
- [ ] New figure, maybe EM
- [x] New three features highlight

Possible features to highlight (tbd):

- Point and click, easy, no code, no R, no Python, no nonsense
- Publication-ready figures
- Citable
- Others?

Plan text in issue prior to update

**Comment by chrtannus** [comment]
<img width="1289" alt="features" src="https://github.com/cytoscape/cytoscape-home/assets/989686/eefd729c-dcb5-4f28-9f8a-13e085f2af6c">
